Реализована задача на первый спринт
prisenkoVO/stellarBurgers pull request #1
Opened 2022-09-11 19:42 UTC by prisenkoVO

Реализованы компоненты App, AppHeader, BurgerConstructor, BurgerIngredients, Modal и ModalOverlay. В процессе реализации создавал вспомогательный компоненты, Модалка реализована через Portal, стили старался писать по БЭМ.
Вынес в отдельный файл повторяющийся PropsType для сущности ингредиентов. Также в проекте лежат интерфейс TS для ингредиентов и TS-овский тип для разновидностей ингредиентов, тк сначала думал сразу писать на TS, тк есть опыт на Ангуляре, но в React оказалось все не такое привычное))

Пардон за позднюю сдачу, в следующий раз буду предусмотрительнее!

2022-09-11 22:46 UTC, serYan1 requested changes
Здравствуйте.

Проделана хорошая работа. Хотелось бы отметить соответствие внешнего вида проекта макету, использование функциональных компонентов, ясный ход мысли использование ts.

Что нужно поправить:
 
 * Импортировать стили как модули.
 * Описать prop-types для компонентов, где это не сделано.
 * Проверять запросы на успешность.
 * Переименовать переменные, в именах которых используются неуместные сокращения.
 * Реализовать закрытие компонента Modal по нажатию клавиши Esc.
 * Поправить дублирование запроса к API при монтировании App.


Что можно улучшить:

* Избавиться от ненужных файлов (data.ts)
* Убрать inline стили
* Использовать оптимизацию вычислений (useCallback и useMemo)
* Избавиться от дублирования кода, закомментированного кода и дублирования разметки (объединение функций, вынос однородной разметки в отдельные компоненты).
* Использовать immutable методы массивов
* Уточнить prop-types в некоторых компонентах
* Использовать константы для категорий элементов и тому подобных вещей

2022-09-11 22:46 UTC, serYan1 commented on src/index.tsx
> +root.render(
Надо исправить: заметил, что getIngredient срабатывает 2 раза при заходе на страницу. Подозреваю, что дело в двойном рендере. Думаю стоит воспользоваться методом ReactDOM.render и передать вторым аргументом root.

2022-09-11 22:46 UTC, serYan1 commented on src/index.tsx
> +// const modalElement = document.createElement('div');
Можно лучше: данный закомментированный код лучше убрать

2022-09-11 22:46 UTC, serYan1 commented on src/components/app-header/app-header.tsx
> +const HeaderBtn = ({ children, title, isNotActive }: HeaderBtnProps) => (
Надо исправить: отлично, что используете ts при описании пропсов, однако согласно ТЗ для компонентов с пропсами необходимо описать propTypes/

2022-09-11 22:46 UTC, serYan1 commented on src/components/app/app.jsx
> +  const getIngredients = async () => {
Надо исправить: необходимо проверять запрос на успешность (response.ok, подробнее - https://developer.mozilla.org/en-US/docs/Web/API/Response/ok, а также на флаг success непосредственно от бекенда), также необходимо добавить блок catch для отлова ошибок. Опционально можно вынести в отдельный файл вместе с константой url и добавить прелоадер.

2022-09-11 22:46 UTC, serYan1 commented on src/components/app/app.jsx
> +  const url = 'https://norma.nomoreparties.space/api/ingredients';
Можно лучше: такие константы лучше писать в uppercase стиле. Подробнее: https://en.wikipedia.org/wiki/Naming_convention_(programming)#:~:text=Constants%20should%20be%20written%20in,not%20as%20the%20first%20character.

2022-09-11 22:46 UTC, serYan1 commented on src/components/modal/modal.jsx
> +  children: PropTypes.object.isRequired,
Можно лучше: можно уточнить тип для children - использовать node вместо object.

2022-09-11 22:46 UTC, serYan1 commented on src/components/modal/modal.jsx
> +export const Modal = ({children, onClose, header}) => {
Надо исправить: согласно ТЗ, кроме клика на оверлей или крестик также необходимо реализовать закрытие модалки по нажатию клавиши Esc. Также не забудьте удалить обработчик после использования :)

2022-09-11 22:46 UTC, serYan1 commented on src/components/ingredient-details/ingredient-details.jsx
> +export const IngredientDetails = (props) => {
Отлично: отлично, что используете функциональные компоненты

2022-09-11 22:46 UTC, serYan1 commented on src/components/ingredient-details/ingredient-details.jsx
> +        <span className="ingredient-details__feature">
Можно лучше: можно заметить, что элемент ingredient-details__feature имеет одинаковую структуру. Соответственно его можно вынести в отдельный компонент дабы избежать дублирования кода.

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/ingredient-card/ingredient-card.jsx
> +  const handleOpenModal = () => {
Можно лучше: handleOpenModal и handleCloseModal можно обернуть в useCallback для оптимизации производительности. Подробнее: https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render

2022-09-11 22:46 UTC, serYan1 commented on src/utils/data.ts
> +export const DATA: Ingredient[] = [
Можно лучше: DATA не используется в проекте, можно убрать

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-constructor/burger-constructor.jsx
> +      [bun, ...mainList].forEach(value => total += value.price);
Можно лучше: функцию расчета полной стоимости бургера лучше переписать на reduce, т.к. reduce семантически больше подходит для этого

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-constructor/burger-constructor.jsx
> +            style={{ flexGrow: '1' }}
Можно лучше: инлайн стилей лучше убрать и добавить требуемые свойства в css класс для читабельности кода и удобства управления стилизацией компонентов.

2022-09-11 22:46 UTC, serYan1 commented on src/components/app-header/app-header.scss
> +.app-header {
Надо исправить: здесь и далее в проекте стили необходимо импортировать как модули. Подробнее: https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const itemsList = ['Булки', 'Соусы', 'Начинки'];
Можно лучше: категории элементов лучше вынести в отдельные константы, чтобыпри необходимости  переиспользовать и случайно не опечататься

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +function filterIngridients(data) {
Можно лучше: вместо forEach и push лучше использовать .filter - он никак не влияет на исходный массив и возвращает новый, что позволяет избавиться от forEach и push

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  filteredData.forEach((value, key) =>
Можно лучше: здесь вместо filteredData можно использовать массив с категориями элементов (itemsList, например), а вместо forEach - .map. Таким образом мы избавимся от необходимости использования структуры Map в filterIngridients и ручного пуша в массив res. Вообще, в реакте при фильтрации и наполнении принято использовать иммутабельные методы массивов: map, filter, reduce: https://proglib.io/p/javascript-map-reduce-filter

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      <div style={{ display: 'flex' }} className="mt-5">
Можно лучше: инлайн стили лучше вынести в классы.

2022-09-11 22:46 UTC, serYan1 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  let res = [];
Надо исправить: название переменной не отражает ее сути

2022-09-11 22:46 UTC, serYan1 commented on src/components/modal/modal.jsx
> +  const headerBlock = (
Можно лучше: думаю, не стоит выносить это в отдельную переменную, т.к нет никакой сложной логики и переиспользования, проще просто добавить это в напрямую в модалку

2022-09-11 22:46 UTC, serYan1 commented on src/components/app-header/app-header.tsx
> +          <HeaderBtn title="Лист заказов" isNotActive={true}>
Можно лучше: думаю все-таки лучше назвать isActive, так будет более читабельно

2022-09-14 21:30 UTC, prisenkoVO commented on src/index.tsx
> +root.render(
Изучил тему
Двойной рендер происходит при таком подходе из-за dev режима в <React.StrictMode>
При использовании ReactDOM.render в React 18, есть предупреждение deprecated
Поэтому здесь менять ничего не стал

2022-09-14 21:31 UTC, prisenkoVO commented on src/index.tsx
> +root.render(
При сборке в production режиме запрос происходит единожды
![image](https://user-images.githubusercontent.com/48548090/190266324-803d78d3-78db-4506-a711-913f4da8f188.png)

2022-09-15 06:43 UTC, serYan1 requested changes
Добрый день! Большая часть замечаний была исправлена, но есть еще 2:

Что нужно исправить:
* Отклонять промис в условиях, чтобы в случае ошибки попасть в catch

Что можно улучшить:
* Завернуть логику добавления/удаления обработчика нажатия на esc в useEffect, заменить keyCode на key

2022-09-15 06:43 UTC, serYan1 commented on src/index.tsx
> +root.render(
Да, вы правы, собирал проект дев режиме, замечание снимаю

2022-09-15 06:43 UTC, serYan1 commented on src/components/app/app.jsx
> +      .catch(error => console.error(error));
Надо исправить: мы не попадем в catch, так как в условиях не реджектится промис

2022-09-15 06:43 UTC, serYan1 commented on src/components/modal/modal.jsx
> +  window.onkeydown = (event) => {
Можно лучше: вместо keyCode лучше использовать key, т.к. keyCode устарел (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), к тому же key возвращает строковое значение клавиши, что позволит нам также избежать использование магической константы 27. Также после размонтирования компонента нужно удалять обработчик, для чего подойдет useEffect

2022-09-16 05:16 UTC, serYan1 reviewed
Здравствуйте. Работа принята.

2022-09-16 08:24 UTC, merged